name: Automated Publish

on:
  push:
    branches: ['main']
    tags: ['v*.*.*']

env:
  CARGO_TERM_COLOR: always
  NPM_CONFIG_PROVENANCE: true

jobs:
  release:
    name: Run publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build with wasm-pack
        run: wasm-pack build --target web --release

      # - name: Setup git
      #   uses: fregante/setup-git-user@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish with npm
        run: npm publish --provenance --access public pkg --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
