name: Automated Release

on:
  push:
    branches: ['main']
    tags: ['v*.*.*']

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Run release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build with wasm-pack
        run: wasm-pack build --target web --release

      - name: Originize Files
        run: tar -czvf rs-crypto.tar.gz -C pkg .

      - name: Publish release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tags: ${{github.ref}}
          prerelease: ${{contains(github.ref, 'alpha') || contains(github.ref, 'beta')|| contains(github.ref, 'rc')}}
          files: |
            rs-crypto.tar.gz

      - name: Clean Files
        run: rm -rf rs-crypto.tar.gz
